spring.application.name=mobile-banking

spring.datasource.url=jdbc:postgresql://mobile.wisoft.dev:10002/donggun
spring.datasource.username=donggun
spring.datasource.password=donggun

server.addreses = 0.0.0.0
server.port = 8080